"""empty message

Revision ID: 6ad2726efb0d
Revises: 0a0a183fee0f
Create Date: 2019-08-25 22:54:36.542178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad2726efb0d'
down_revision = '0a0a183fee0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('total_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'total_price')
    # ### end Alembic commands ###
